/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DateRangePicker: typeof import('./src/components/date-range-picker.vue')['default']
    HelloWorld: typeof import('./src/components/hello-world.vue')['default']
  }
}
